### ISSUE TITLE
i18n dependency conflict

### ISSUE THREAD

**Issue by juddkussrow** [zapnap/bitbank#1]
What version of rails are you using where you have activesupport >= 3.0.7 and i18n >= 0.6.0 !?!?  Bundler tells me that rails ~> 3.0.7 requires i18n 0.5.0

If I use rails 3.1.0.rc4 to get i18n 0.6.0 then bundler complains that bitbank needs that older version of activesupport.  I don't see how there could be a way to override rails to use a newer version of i18n ...

**Comment by zapnap** [comment]
I'm not seeing any problems with this locally (obviously, I'm using AS 3.1.0 instead of 3.0.7 though, which satisfies the gem criteria). That said, there's nothing specific about 0.6.0 that's required for Bitbank; feel free to submit a pull request with the 0.5.0 dependency. Thanks.

**Comment by juddkussrow** [comment]
So, there isn't a way to use this gem with rails 3.0?  Might want to add that to the ReadMe if you are not going to roll the Gemfile back to >= 0.5.0

Can you send me your local Gemfile for the app that you are testing it out with?

I've never forked a repository before.  What needs to go down for me to install my own version of the gem?

**Comment by zapnap** [comment]
I've just pushed a new gem with the changes. Try using that.
